### ISSUE TITLE
【问题】用户名和分数适合存放到session里

### ISSUE THREAD

**Issue by wolfogre** [yishougushici/Document#10]
<%=request.getAttribute("score")%>和<%=request.getAttribute("username")%>
考虑写成
<%=session.getAttribute("score")%>和<%=session.getAttribute("username")%>
绝大多数页面上这两个值是不变的，分数如果有变化我会更新score，所以放在session里能省去我很多事。

**Comment by zhaokuohaha** [comment]
搞定
