### ISSUE TITLE
【问题】右上角的分数不确定显示那一个分数

### ISSUE THREAD

**Issue by wolfogre** [yishougushici/Document#11]
目前是三个分数都显示，不是很好看
![image](https://cloud.githubusercontent.com/assets/9418365/15291381/1ba3a740-1bb0-11e6-9929-a0cfae13d1c0.png)

**Comment by zhaokuohaha** [comment]
实现这样的功能有没有可能:
当只有进入相关游戏页面的时候, 才显示相应的游戏分数. 
没有进入游戏页面之前就只显示心, 或者什么都不显示

**Comment by wolfogre** [comment]
没问题。

**Comment by wolfogre** [comment]
那还是把分数放在request里吧，你先改回<%=request.getAttribute("score")%>

**Comment by zhaokuohaha** [comment]
ok, 已修改
