### ISSUE TITLE
【问题】诗词推荐的状态

### ISSUE THREAD

**Issue by zhaokuohaha** [yishougushici/Document#13]
诗词推荐的`**ispass**`状态目前是不是只有两个值

需求的状态应该有三种: 
1. 未审核
2. 审核未通过
3. 审核通过

**Comment by wolfogre** [comment]
1. 未审核 -> N(No)
2. 审核未通过 -> I(Ignore)
3. 审核通过 -> Y(Yes)

如何？那原创诗词也要改吗？

**Comment by zhaokuohaha** [comment]
也一起改

**Comment by wolfogre** [comment]
搞定，数据库不用改。
