### ISSUE TITLE
【原创诗词报错】 origin Action 的 add 方法报错

### ISSUE THREAD

**Issue by zhaokuohaha** [yishougushici/Document#15]
HTTP Status 500 - Unknown entity: gushici.domain.Original

**Comment by wolfogre** [comment]
哦哦，那是因为我更新了hibernate.cfg.xml,但是它不被git跟踪。
你把hibernate.cfg.xml最后几句改成如下：

> ```
> 
> <mapping class="gushici.domain.User"/>
> <mapping class="gushici.domain.PushRecord"/>
> <mapping class="gushici.domain.Feedback"/>
> <mapping class="gushici.domain.Recommend"/>
> <mapping class="gushici.domain.Original"/>
> ```

**Comment by zhaokuohaha** [comment]
成功
