### ISSUE TITLE
【问题】诗词接龙回答超时后重新开始

### ISSUE THREAD

**Issue by zhaokuohaha** [yishougushici/Document#19]
需求: 
假设A,B双方玩游戏, 当A接龙超时之后.游戏重新开始
由A开始
也就是说保持原有的答题顺序不变, 但是存在诗词记录栈里面的信息要清一下,
 可以保留最后一条,这样既防止耍赖, 也方便你记录答题顺序

实现起来有问题吗?

**Comment by wolfogre** [comment]
可以，我给你开一个清理诗词记录栈的接口，但其他的事我就没法插手了。你前端能搞定我后台就没问题。

**Comment by wolfogre** [comment]
“A接龙超时之后，游戏重新开始，由A开始”，如果清空了，后台并不知道谁应该先开始答题。而如你所说，保留最后一条，即保留B答题的记录，那么A说的第一句必须要接B的龙，这就不是重新开始了。

**Comment by zhaokuohaha** [comment]
OK, 后台只管清空.  
谁先开始的逻辑我来处理.
重新开始的路由: `round/restart`

**Comment by wolfogre** [comment]
已实现，没测试。

**Comment by zhaokuohaha** [comment]
初步测试通过
