### ISSUE TITLE
【问题】管理员的路由修改

### ISSUE THREAD

**Issue by wolfogre** [yishougushici/Document#22]
管理员的路由我们统一下：
admin/getFeedback
admin/setFeedback
admin/getRecommend
admin/setRecommend
admin/getOriginal
admin/setOriginal
admin/submitUpdate
顾名可思义

**Comment by zhaokuohaha** [comment]
至于修改成哪种状态, 用参数来传递吗?

我思考了一下, 对于一条留言/推荐/原创  管理员应该有以下几种行为
1. 通过  数据库设为Y  下次读取时不再读取
2. 不通过 数据库设为N 下次不读取
3.下一条  本条数据不处理, 直接拿下一条
4. 删除   直接删除该条数据(主要针对诗词推荐等功能, 如果用户随便输入, 可删)

突然想到第4条不用了.   保留数据. 给数据库写个触发器, 给每个用户设置个不通过上限就行了哈哈哈哈

**Comment by zhaokuohaha** [comment]
我更新了原创诗词(Original)的前端代码, 你后台看看这个逻辑有没有问题

**Comment by wolfogre** [comment]
明天再说

**Comment by wolfogre** [comment]
这样：
你请求getXXX，参数是一个Id，Id是当前处理的记录的Id，如果当前没有，给-1；
我会给出这个Id的下一条未处理的记录，如果没有下一条，我就取第一条，如果再没有，result为false；
我会给你一条未处理的记录，result为true，data为该记录的所有信息，包括Id和其他信息；
如果你选择处理，请求setXXX，参数是Id和处理结果，分为Y（同过），I（拒绝），不是N，N表示未处理；
如果你选择不处理，请求getXXX，参数是一个Id，Id是当前处理的记录的Id，如果当前没有，给-1。

**Comment by zhaokuohaha** [comment]
ok  明天写.  先睡觉

**Comment by zhaokuohaha** [comment]
getxxx有两个参数:
`id: 当前项的id`
`mode: 请求方式, 分别为: next(下一条)    previous(上一条)`

ajax请求:

``` javascript
$.ajax({
    url:"..."
    data:{"id":-1, "mode":"next"}
});
```

**Comment by zhaokuohaha** [comment]
setxxx请求样式:

``` javascript
$.ajax({
    url:"..."
    data:{"id":34, "option":"Y"}
});
```

**Comment by wolfogre** [comment]
getOriginal返回样式：
{
  "result": true,
  "data": {
    "sorin_auth": "12",
    "sorin_content": "12",
    "sorin_id": 3,
    "sorin_pass": "N",
    "sorin_time": "2016-05-18T17:18:30",
    "sorin_title": "12"
  }
}

**Comment by wolfogre** [comment]
getRecommend返回样式：
{
  "result": true,
  "data": {
    "srec_auth": "哈哈哈",
    "srec_content": "哈哈哈哈哈，\r\n哈哈哈哈哈，\r\n哈哈哈哈哈，\r\n哈哈哈哈哈。",
    "srec_id": 5,
    "srec_pass": "N",
    "srec_reson": "哈哈哈哈！",
    "srec_suser": "wolf",
    "srec_time": "2016-05-15T17:31:25",
    "srec_title": "哈"
  }
}

**Comment by wolfogre** [comment]
getFeedback返回样式：
{
  "result": true,
  "data": {
    "sfb_content": "1212",
    "sfb_date": "2016-05-21T00:00:00",
    "sfb_id": 5,
    "sfb_pass": "N",
    "sfb_public": true,
    "sfb_user": "12"
  }
}
