### ISSUE TITLE
界面设计问题记录

### ISSUE THREAD

**Issue by wolfogre** [yishougushici/Document#6]
# 界面设计问题记录

**Comment by wolfogre** [comment]
有些页面的用户名和分数不用显示。

**Comment by wolfogre** [comment]
如果页面可以显示用户名和分数，应该直接从session里拿。

**Comment by wolfogre** [comment]
登录界面密码是明文。

**Comment by wolfogre** [comment]
登录界面样式出现问题的原因在于“新用户?点击注册”文字，其他页面正常！

**Comment by wolfogre** [comment]
考虑将layoutHead.jsp里的<%=request.getAttribute("tagTitle")%>和<%=request.getAttribute("pageTitle")%>合成同一个。比如都是pageTitle。

**已修正**

**Comment by wolfogre** [comment]
查询诗词界面错误很严重，很多标签文字不对，诗句字体大的吓人

**Comment by wolfogre** [comment]
注册界面没有表单验证，密码明文，没有密码确认。

**Comment by zhaokuohaha** [comment]
前端获取
用户名:`<%=session.getAttribute("username")%>`
分数:`<%=session.getAttribute("score")%>`

**Comment by zhaokuohaha** [comment]
像上面的issue可以回复吗? 还是只能编辑

**狼煞回复**：我们可以自己动手回复哇。
