### ISSUE TITLE
【问题】用户的分数字段为空

### ISSUE THREAD

**Issue by wolfogre** [yishougushici/Document#8]
可以考虑将分数字段设为非空，默认值为零，朝增考虑下。

**Comment by zhaokuohaha** [comment]
**是应该这样**
否则程序这边double为空会报异常.  但是现在数据库我动不了

**Comment by wolfogre** [comment]
我怀疑是因为已经有数据是空了，变为非空才出现死锁的问题，再重启一下数据库，把分数都填上0，在变为非空试试。show processlist;看死锁

**Comment by zhaokuohaha** [comment]
我看了一下, 已经好了
